<?php echo $this->doctype(); ?>
<html lang="en">
    <?php echo $this->partial('head'); ?>
    <body>

        <?php echo $this->partial('nav'); ?>

        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <?php echo $this->content; ?>
                </div>
                <div class="col-md-4">
                    <?php if ($this->sidebar) {?>
                        <?php echo $this->sidebar;?>
                    <?php } ?>
                </div>
            </div>

            <hr>
            <?php echo $this->partial('footer'); ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
