<?php
$title = 'Add new album';
/** @var \Zend\View\Renderer\PhpRenderer $this */
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
/** @var \Zend\Form\Form $form */
$form->setAttribute('action', $this->url('product-create'));
$form->prepare();

$form1 = new \Zend\Form\View\Helper\Form();
echo $form1->openTag($form);
$row = new \Zend\Form\View\Helper\FormRow();
var_dump($row->render($form->get('category_id')));
echo $form1->closeTag();

echo $this->form(null, null)->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('category_id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();