<?php
$title = 'Edit album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
/** @var \Zend\Form\Form $form */
/** @var \Admin\Model\Product $model */
$form->setAttribute('action', $this->url('product-edit', ['id' => $model->id]));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('category_id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();